### ISSUE TITLE
TypeScript: doesn't work with "useDefineForClassFields" : true

### ISSUE THREAD

**Issue by sorteam** [LabEG/first-di#2]
Injected with `@autowired()` objects are undefined

**Comment by bolotin-taptima** [comment]
I confirm injected class fields are undefined. My tsconfig.json
```
{
    "compilerOptions": {
        "strict": true,
        "baseUrl": "./src",
        "jsx": "preserve",
        "allowSyntheticDefaultImports": true,
        "target": "es5",
        "lib": ["dom", "dom.iterable", "esnext"],
        "allowJs": true,
        "skipLibCheck": true,
        "forceConsistentCasingInFileNames": true,
        "noEmit": true,
        "esModuleInterop": true,
        "module": "esnext",
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "experimentalDecorators": true,
        "useDefineForClassFields": true,
        "emitDecoratorMetadata": true
    },
    "exclude": ["node_modules"],
    "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"]
}
```

**Comment by LabEG** [comment]
Sory for long response. Yes, there is such a problem. This is because decorators work at code initialization stage and define properties marked by decorator autowired before creation of class instancing. But if you use useDefineForClassFields option, this property will rewritted during creation of class instances. Also typescript does not allow to transfer logic of decorator to option useDefineForClassFields.

Therefore, for using first-di libraries with options useDefineForClassFields you can use API directly. As in [this examples](https://github.com/LabEG/first-di#api).

`
import { resolve } from "first-di";

const service = resolve(ApiService3);
`

**Comment by sorteam** [comment]
> Sory for long response. Yes, there is such a problem. This is because decorators work at code initialization stage and define properties marked by decorator autowired before creation of class instance. But if you use useDefineForClassFields option, this property will rewritted during creation of class instances. Also typescript does not allow to transfer logic of decorator to option useDefineForClassFields.
> 
> Therefore, for using first-di libraries with options useDefineForClassFields you can use API directly. As in [this examples](https://github.com/LabEG/first-di#api).
> 
> ```
> import { resolve } from "first-di";
> 
> const service = resolve(ApiService3);
> ```

resolve doesn't work with abstract class...

**Comment by bolotin-taptima** [comment]
Im my case `@autowired()` does not work no matter 'useDefineForClassFields' options set to `true` or `false`.

Using `resolve` function as described in the [doc](https://github.com/LabEG/first-di#api) produce an error
```
TS2345: Argument of type 'typeof ApiService3' is not assignable to parameter of type 'ClassConstructor< ApiService3>'. Cannot assign an abstract constructor type to a non-abstract constructor type.
```
So when I suppress this error with `@ts-ignore` everything works as expected, but how to avoid using `@ts-ignore`? Or better make `@autowired()` work...
